Repository CPNV-ES/MAW11_Mugiwaras_Looper, pull requests merged in 2023-12, with the labels that each got.

#21 List all results of an exercise
  src/controllers/ExercisesController.php
  src/models/Exercise.php
  src/views/headers/resultsHeader.php
  src/views/results.php
Labels: enhancement, backend, frontend

#20 Feature/fulfillments exercise
  composer.json
  public/css/app.css
  public/index.php
  src/controllers/ExercisesController.php
  src/models/Exercise.php
  src/views/fulfillments.php
  src/views/fulfillmentsEdit.php
  src/views/headers/fulfillmentsHeader.php
  src/views/layout.php
Labels: enhancement, backend, frontend

#26 Display field answers
  public/index.php
  src/controllers/ResultController.php
  src/models/Exercise.php
  src/views/fieldResults.php
Labels: enhancement, backend, frontend

#31 Refactor controller
  public/index.php
  src/controllers/AnswersController.php
  src/controllers/ExercisesController.php
  src/controllers/FieldsController.php
  src/controllers/FulfillmentController.php
  src/controllers/ResultsController.php
  src/controllers/baseController.php
Labels: refactor, backend

#34 Show index fulfillment and delete them
  public/index.php
  src/controllers/FulfillmentController.php
  src/models/Exercise.php
  src/views/exerciseFulfillments.php
Labels: backend, frontend

#32 add the id_fulfillment and id_field to the urls
  src/controllers/ResultsController.php
  src/views/results.php
Labels: refactor, backend, frontend

#35 Refactor renderer
  public/index.php
  src/controllers/DashboardController.php
  src/controllers/ExercisesController.php
  src/controllers/FieldsController.php
  src/controllers/FulfillmentController.php
  src/controllers/ResultsController.php
  src/controllers/baseController.php
  src/views/answering.php
  src/views/createExercise.php
  src/views/dashboard.php
  src/views/editField.php
  src/views/exerciseFulfillments.php
  src/views/fieldResults.php
  src/views/fulfillment.php
  src/views/fulfillments.php
  src/views/fulfillmentsEdit.php
  src/views/headers/answeringHeader.php
  src/views/headers/createExerciseHeader.php
  src/views/headers/dashboardHeader.php
  src/views/headers/exerciseNameHeader.php
  src/views/headers/fulfillmentsHeader.php
  src/views/headers/layoutHead.php
  src/views/headers/manageHeader.php
  src/views/headers/newFieldsHeader.php
  src/views/headers/resultsHeader.php
  src/views/layout.php
  src/views/manageExercise.php
  src/views/newFields.php
  src/views/results.php
Labels: refactor, backend

#36 Add the textarea when the value kind is multiline
  src/views/fulfillments.php
Labels: frontend

#38 Implement query builder
  src/models/DatabaseConnection.php
  src/models/Exercise.php
Labels: enhancement, refactor

#39 Refactor model
  composer.json
  src/controllers/DashboardController.php
  src/controllers/ExercisesController.php
  src/controllers/FieldsController.php
  src/controllers/FulfillmentController.php
  src/controllers/ResultsController.php
  src/controllers/baseController.php
  src/core/Renderer.php
  src/models/AnswerModel.php
  src/models/Exercise.php
  src/models/exerciseModel.php
  src/models/fieldModel.php
  src/models/fulfillmentModel.php
Labels: refactor, backend

#41 Release/1.0.0
  .env.example
  .gitignore
  README.md
  composer.json
  db_looper.sql
  public/css/app.css
  public/img/logo.png
  public/index.php
  public/js/rails.js
  src/controllers/DashboardController.php
  src/controllers/ErrorController.php
  src/controllers/ExercisesController.php
  src/controllers/FieldsController.php
  src/controllers/FulfillmentController.php
  src/controllers/ResultsController.php
  src/models/AnswerModel.php
  src/models/exerciseModel.php
  src/models/fieldModel.php
  src/models/fulfillmentModel.php
  src/views/answering.php
  src/views/createExercise.php
  src/views/dashboard.php
  src/views/editField.php
  src/views/error404.php
  src/views/exerciseFulfillments.php
  src/views/fieldResults.php
  src/views/fulfillment.php
  src/views/fulfillments.php
  src/views/fulfillmentsEdit.php
  src/views/headers/answeringHeader.php
  src/views/headers/createExerciseHeader.php
  src/views/headers/dashboardHeader.php
  src/views/headers/fulfillmentsHeader.php
  src/views/headers/manageHeader.php
  src/views/headers/newFieldsHeader.php
  src/views/headers/resultsHeader.php
  src/views/layout.php
  src/views/manageExercise.php
  src/views/newFields.php
  src/views/results.php
Labels: backend
